package app.model 
{
	/**
	 * ...
	 * @author joe
	 */
	public class StaticImageUrl 
	{
		public static var commonImageKeys:Array = [
		
"alert_body_bg",
"alert_button_bg",
"alert_button_bg_press",
"alert_close",
"btn_chn",
"btn_chn_press",
"btn_detail",
"btn_detail_press",
"btn_eng",
"btn_eng_press",
"btn_jpn",
"btn_jpn_press",
"btn_kor",
"btn_kor_press",
"btn_location",
"btn_location_press",
"btn_location_big",
"btn_location_big_press",
"btn_next",
"btn_next_press",
"btn_page",
"btn_page_focus",
"btn_page_press",
"btn_prev",
"btn_prev_press",
"btn_search",
"btn_search_category",
"btn_search_category_press",
"btn_search_press",
"desc_language",
"floor_num_1F",
"floor_num_1F_click",
"floor_num_1F_cur",
"floor_num_1F_sel",
"floor_num_2F",
"floor_num_2F_click",
"floor_num_2F_cur",
"floor_num_2F_sel",
"floor_num_3F",
"floor_num_3F_click",
"floor_num_3F_cur",
"floor_num_3F_sel",
"floor_num_4F",
"floor_num_4F_click",
"floor_num_4F_cur",
"floor_num_4F_sel",
"floor_num_5F",
"floor_num_5F_click",
"floor_num_5F_cur",
"floor_num_5F_sel",
"floor_num_B1F",
"floor_num_B1F_click",
"floor_num_B1F_cur",
"floor_num_B1F_sel",
"floor_num_click",
"floor_num_cur",
"floor_num_sel",
"footer",
"header",
"header_time1",
"header_time2",
"header_time3",
"icon_brand_list",
"main_menu_item_press",
"main_shopping_info",
"map_back_floor_plan",
"map_back_location_info1",
"map_back_location_info2",
"map_EAST1_B1F",
"map_EAST2_1F",
"map_EAST3_2F",
"map_EAST4_3F",
"map_EAST5_4F",
"map_GA_click",
"map_icon_activation",
"map_icon_activation_click",
"map_WEST1_B1F",
"map_WEST2_1F",
"map_WEST3_2F",
"map_WEST4_3F",
"map_WEST5_4F",
"map_WEST6_5F",
"menu_item1",
"menu_item1_press",
"menu_item2",
"menu_item2_press",
"menu_item3",
"menu_item3_press",
"menu_item4",
"menu_item4_press",
"menu_item5",
"menu_item5_press",
"menu_item6",
"menu_item6_press",
"search_field",
"tab_category",
"tab_category_press",
"tab_east",
"tab_east_focus",
"tab_east_press",
"tab_search",
"tab_search_press",
"tab_west",
"tab_west_focus",
"tab_west_press",
"shop_list_item_bg",
"shop_list_item_bg_press",
"shop_list_item_bg_focus",
"scroll_bg",
"handle",
"handle_press",
"search_close",
"search_close_press",
"category_item",
"category_item_press",
"map_back_location_info1",
"map_back_location_info2",
"1-1_downarrow",
"1-1_uparrow",
"1-2_downarrow",
"1-2_uparrow",
"1-3_downarrow",
"1-3_uparrow",
"1-4_downarrow",
"1-4_uparrow",
"1-5_downarrow",
"1-5_uparrow",
"1-6_downarrow",
"1-6_uparrow",
"2-2_downarrow",
"2-2_uparrow",
"2-3_downarrow",
"2-3_uparrow",
"3-2_downarrow",
"3-2_uparrow",
"3-3_downarrow",
"3-3_uparrow",
"4-2_downarrow",
"4-2_uparrow",
"4-3_downarrow",
"4-3_uparrow",
"5-2_downarrow",
"5-2_uparrow",
"5-3_downarrow",
"5-3_uparrow",
"next_btn",
"next_btn_press",
"prev_btn",
"prev_btn_press"

		];
		
		public static var imageKeys:Array = [
		
			"galleria_service", 
			"main_menu", 
			"title_brand_search", 
			"title_floor_guide", 
			"title_select_language", 
			"title_shopping_info",
			"title_ranking",
			"brand_info",
			"location_info",
			"map_GA",
			"map_icon_here",
			"destination",
			"alert_nodata_brand",
			"alert_nodata_search",
			"alert_screensaver",
			"key1",
			"key2",
			"key3"
		];
		
		public static function getUrl(key:String, lang:String=null):String
		{
			var path:String = "images/static/common/";
			
			if (lang)
			{
				path = "images/static/" + lang + "/";
			}
			
			return path + key + ".png";
		}
		
	}

}




